# Generated by Django 3.1.6 on 2021-02-13 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='page title')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='slug')),
                ('shown_in_navbar', models.BooleanField(default=False, verbose_name='include in navigation')),
                ('base', models.CharField(blank=True, choices=[('HOME', 'Home Page'), ('ABOUT', 'About Us'), ('CONTACT', 'Contact Form'), ('REGISTER', 'New Member Registration')], max_length=8, null=True, unique=True, verbose_name='base page')),
            ],
            options={
                'verbose_name': 'Web Page',
                'verbose_name_plural': 'Web Pages',
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.IntegerField(choices=[(0, 'Anonymous/Guests Only'), (1, 'Public'), (2, 'Members Only')], default=2, verbose_name='content visibility')),
                ('heading', models.CharField(blank=True, max_length=128, verbose_name='heading')),
                ('body', models.TextField(verbose_name='body')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='pages.page')),
            ],
            options={
                'verbose_name': 'Content Block',
                'verbose_name_plural': 'Content Blocks',
                'order_with_respect_to': 'page',
            },
        ),
    ]
