# Generated by Django 3.1.6 on 2021-02-16 06:33

from django.db import migrations, models
import django.db.models.deletion
import project.messaging.models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'get_latest_by': 'date_modified', 'ordering': ['-date_modified'], 'verbose_name': 'message', 'verbose_name_plural': 'messages'},
        ),
        migrations.AlterField(
            model_name='mailbox',
            name='folder',
            field=models.IntegerField(choices=[(1, 'Inbox'), (2, 'Archive'), (3, 'Trash')], default=1, verbose_name='folder'),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=project.messaging.models.get_attachment_path, verbose_name='file')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='messaging.message')),
            ],
            options={
                'verbose_name': 'attachment',
                'verbose_name_plural': 'attachments',
            },
        ),
    ]
